### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by lazywhite** [start-angular/SB-Admin-BS4-Angular-2#10]
```
_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/white/SB-Admin-BS4-Angular-2/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/Users/white/SB-Admin-BS4-Angular-2/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
[11:10:17] 'serve' errored after 6.08 s
[11:10:17] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build.sass.dev'.
[11:10:17] 'build.dev' errored after 4.83 s
[11:10:17] Error in plugin 'run-sequence'
Message:
    An error occured in task 'serve'.
[11:10:17] 'build.dev' errored after 4.84 s
[11:10:17] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build.sass.dev'.
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/white/SB-Admin-BS4-Angular-2/npm-debug.log
```

**Comment by nitinkumarmishra** [comment]
install  node 4.* LTS it will fix the issue
`https://nodejs.org/dist/v4.4.4/node-v4.4.4.pkg`
