### ISSUE TITLE
npm start error (node v4.4.4)

### ISSUE THREAD

**Issue by lazywhite** [start-angular/SB-Admin-BS4-Angular-2#11]
```
[20:40:46] Starting 'clean.dist'...
[20:40:46] Deleted -
[20:40:46] Finished 'clean.dist' after 8.95 ms
[20:40:46] Starting 'tslint'...
[20:40:48] Finished 'tslint' after 1.88 s
[20:40:48] Starting 'build.sass.dev'...
[20:40:48] 'build.sass.dev' errored after 18 ms
[20:40:48] Error: ENOENT: no such file or directory, scandir '/Users/white/SB-Admin-BS4-Angular-2/node_modules/.npminstall/node-sass/3.7.0/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/Users/white/SB-Admin-BS4-Angular-2/node_modules/.npminstall/node-sass/3.7.0/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/Users/white/SB-Admin-BS4-Angular-2/node_modules/.npminstall/node-sass/3.7.0/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/white/SB-Admin-BS4-Angular-2/node_modules/.npminstall/node-sass/3.7.0/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/white/SB-Admin-BS4-Angular-2/node_modules/.npminstall/node-sass/3.7.0/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/Users/white/SB-Admin-BS4-Angular-2/node_modules/.npminstall/node-sass/3.7.0/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
[20:40:48] 'serve' errored after 7.06 s
[20:40:48] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build.sass.dev'.
[20:40:48] 'build.dev' errored after 5.65 s
[20:40:48] Error in plugin 'run-sequence'
Message:
    An error occured in task 'serve'.
[20:40:48] 'build.dev' errored after 5.65 s
[20:40:48] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build.sass.dev'.

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/white/.nvm/versions/node/v4.4.4/bin/node" "/Users/white/.nvm/versions/node/v4.4.4/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/white/SB-Admin-BS4-Angular-2/npm-debug.log
```

**Comment by nitinkumarmishra** [comment]
is there any error in npm install
