### ISSUE TITLE
error 404 on bs-component.component.html

### ISSUE THREAD

**Issue by longinous** [start-angular/SB-Admin-BS4-Angular-2#31]
downloaded zip
extracted
npm install
npm start
browser stuck:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
Unhandled Promise rejection: Failed to load http://localhost:5555/app/dashboard/bs-component/bs-component.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load http://localhost:5555/app/dashboard/bs-component/bs-component.component.html undefined
Error: Uncaught (in promise): Failed to load http://localhost:5555/app/dashboard/bs-component/bs-component.component.html(…)
```
if I try
`gulp build.prod`
output is
```
[...]
[00:58:26] Starting 'build.js.prod'...
Error: ENOENT: no such file or directory, open '/home/roberto/tinbroker-dev-frontend/dist/tmp/app/dashboard/bs-component/bs-component.component.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at getFileData (/home/*deleted*/node_modules/gulp-inline-ng2-template/parser.js:281:17)
    at /home/*deleted*/node_modules/gulp-inline-ng2-template/parser.js:245:22
    at /home/*deleted*/node_modules/async/dist/async.js:3671:13
    at replenish (/home/*deleted*/node_modules/async/dist/async.js:884:21)
    at /home/*deleted*/node_modules/async/dist/async.js:888:13
    at eachOfLimit (/home/*deleted*/node_modules/async/dist/async.js:915:26)
    at /home/*deleted*/node_modules/async/dist/async.js:920:20
    at _parallel (/home/*deleted*/node_modules/async/dist/async.js:3670:9)
```

**Comment by longinous** [comment]
problem found in src/client/app/dashboard/bs-component/bsComponent.component.ts
line 7
from
`    templateUrl: './bs-component.component.html',
`
to
`    templateUrl: './bs-Component.component.html',`
