### ISSUE TITLE
npm start failed ( gulp serve --env dev)

### ISSUE THREAD

**Issue by wiseflat** [start-angular/SB-Admin-BS4-Angular-2#4]
Hi, 

I would like to test your wonderful UI. But I have a problem to start the server...
Do you have any ideas ? 
Cheers

```
# npm start

> angular2-seed@0.0.0 start /opt/SB-Admin-BS4-Angular-2
> gulp serve --env dev

[13:47:08] Requiring external module ts-node/register
----------------------------------
⨯ Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
tools/config.ts (1,28): Cannot find module 'fs'. (2307)
tools/config.ts (2,20): Cannot find module 'yargs'. (2307)
tools/config.ts (3,31): Cannot find module 'path'. (2307)
tools/config.ts (13,52): Cannot find name '__dirname'. (2304)
tools/config.ts (119,50): Cannot find name 'require'. (2304)
tools/manual_typings/merge-stream.d.ts (2,36): Cannot find namespace 'NodeJS'. (2503)
tools/manual_typings/merge-stream.d.ts (3,33): Cannot find namespace 'NodeJS'. (2503)
tools/manual_typings/merge-stream.d.ts (4,17): Cannot find namespace 'NodeJS'. (2503)
tools/utils.ts (9,17): Cannot find name 'require'. (2304)
tools/utils/code_change_tools.ts (1,26): Cannot find module 'express'. (2307)
tools/utils/code_change_tools.ts (6,20): Cannot find module 'path'. (2307)
tools/utils/code_change_tools.ts (45,18): Cannot find name 'process'. (2304)
tools/utils/server.ts (3,23): Cannot find module 'gulp-util'. (2307)
tools/utils/server.ts (4,26): Cannot find module 'express'. (2307)
tools/utils/server.ts (6,30): Cannot find module 'serve-static'. (2307)
tools/utils/server.ts (8,23): Cannot find module 'path'. (2307)
tools/utils/server.ts (32,25): Cannot find name 'process'. (2304)
tools/utils/tasks_tools.ts (1,23): Cannot find module 'gulp'. (2307)
tools/utils/tasks_tools.ts (2,23): Cannot find module 'gulp-util'. (2307)
tools/utils/tasks_tools.ts (3,24): Cannot find module 'chalk'. (2307)
tools/utils/tasks_tools.ts (4,34): Cannot find module 'gulp-load-plugins'. (2307)
tools/utils/tasks_tools.ts (5,31): Cannot find module 'run-sequence'. (2307)
tools/utils/tasks_tools.ts (6,50): Cannot find module 'fs'. (2307)
tools/utils/tasks_tools.ts (7,20): Cannot find module 'path'. (2307)
tools/utils/tasks_tools.ts (19,10): Cannot find name 'require'. (2304)
tools/utils/template_injectables.ts (4,20): Cannot find module 'path'. (2307)
----------------------------------

npm ERR! Linux 2.6.32-042stab111.12
npm ERR! argv "/root/.nvm/versions/node/v5.9.1/bin/node" "/root/.nvm/versions/node/v5.9.1/bin/npm" "start"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/SB-Admin-BS4-Angular-2/npm-debug.log
```

This is the content of the log file :+1: 
```
more /opt/SB-Admin-BS4-Angular-2/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v5.9.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v5.9.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.7.3
3 info using node@v5.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-seed@0.0.0~prestart: angular2-seed@0.0.0
6 silly lifecycle angular2-seed@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-seed@0.0.0~start: angular2-seed@0.0.0
8 verbose lifecycle angular2-seed@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@0.0.0~start: PATH: /root/.nvm/versions/node/v5.9.1/lib/node_modules/npm/bin/node-gyp-bin:/opt/SB-Admin-BS4-Angular-2/node_modules/.bin:/root/.nvm/versions/node/v5.9.1/bin:/root/.nvm/versions/node/v5.9.1/bin:/usr/local/sbin:/usr
/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle angular2-seed@0.0.0~start: CWD: /opt/SB-Admin-BS4-Angular-2
11 silly lifecycle angular2-seed@0.0.0~start: Args: [ '-c', 'gulp serve --env dev' ]
12 silly lifecycle angular2-seed@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-seed@0.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-seed@0.0.0 start: `gulp serve --env dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v5.9.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v5.9.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed@0.0.0
16 verbose cwd /opt/SB-Admin-BS4-Angular-2
17 error Linux 2.6.32-042stab111.12
18 error argv "/root/.nvm/versions/node/v5.9.1/bin/node" "/root/.nvm/versions/node/v5.9.1/bin/npm" "start"
19 error node v5.9.1
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error angular2-seed@0.0.0 start: `gulp serve --env dev`
22 error Exit status 1
23 error Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve --env dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by nitinkumarmishra** [comment]
Just remove your node entirely and install a fresh node(LTS  v4.4.1) from the following link
https://nodejs.org/en/

**Comment by wiseflat** [comment]
Hi,
```
# nvm --version
0.31.0
# nvm version node
v5.9.1
```

I have installed node with nvm. Maybe I can use your project with an older version of node?

**Comment by nitinkumarmishra** [comment]
which OS are you using ?

**Comment by wiseflat** [comment]
Debian wheezy

**Comment by nitinkumarmishra** [comment]
npm 3 expand the node module in a different way in comparison to npm 2 and we developed project using npm 2 so you have to install node (LTS) it will work fine

**Comment by shiversamar** [comment]
missing script: build:/Users/amar/Desktop/SB-Admin-BS4-Angular-4/npm-debug.log, I'm getting this error if any chance anyone knows the answer or the code perhaps
