### ISSUE TITLE
Error when I prod build with AoT compilation

### ISSUE THREAD

**Issue by Yamilquery** [start-angular/SB-Admin-BS4-Angular-2#58]
I'm getting this error when I prod build with AoT compilation:

**npm run build.prod.exp**

Error: Unexpected value 'CarouselModule' imported by the module 'HomeModule'
    at /Users/yamildiazaguirre/Documents/node/yamquery/SB-Admin-BS4-Angular-2/node_modules/@angular/compiler/bundles/compiler.umd.js:14126:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/yamildiazaguirre/Documents/node/yamquery/SB-Admin-BS4-Angular-2/node_modules/@angular/compiler/bundles/compiler.umd.js:14111:46)
    at /Users/yamildiazaguirre/Documents/node/yamquery/SB-Admin-BS4-Angular-2/node_modules/@angular/compiler/bundles/compiler.umd.js:12952:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/Users/yamildiazaguirre/Documents/node/yamquery/SB-Admin-BS4-Angular-2/node_modules/@angular/compiler/bundles/compiler.umd.js:12951:21)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:110:45)
    at codegen (/Users/yamildiazaguirre/Documents/node/yamquery/SB-Admin-BS4-Angular-2/tools/tasks/seed/compile.ahead.prod.ts:14:69)
    at Object.main (/Users/yamildiazaguirre/Documents/node/yamquery/tools/@angular/tsc-wrapped/src/main.ts:44:12)
    at module.exports (/Users/yamildiazaguirre/Documents/node/yamquery/SB-Admin-BS4-Angular-2/tools/tasks/seed/compile.ahead.prod.ts:32:7)
Compilation failed

I'm using OS X
My node version is
v6.9.1

My npm version is
3.10.8

**Comment by Yamilquery** [comment]
That hurts because it is an excellent template, but it is extremely slow in production. :(

**Comment by nitinkumarmishra** [comment]
Will debug it and fix it soon. For now you can try `gulp build.prod`

**Comment by palorr** [comment]
![37](https://cloud.githubusercontent.com/assets/8223314/20651797/593fc16e-b4f4-11e6-89c8-0546e8a887d8.png)
When I try to create my prod folder i take this
